name = "RayTracer"
uuid = "0921820f-ef62-4682-a38b-856f410923bd"
authors = ["Mohamed Kamal AbdElrahman"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
